### ISSUE TITLE
Suggestions to improve the lib

### ISSUE THREAD

**Issue by abderraouf-adjal** [RippoZero/WattCalc#1]
Hello @RippoZero.
I hope you don't mind this quickly written review.

- The file `library.properties` is an important description file for development platforms such as Arduino IDE and PlatformIO, which you describe the version and which Architectures and boards your code can work on. beside that the description file will help understanding the library, it will help putting it in Arduino IDE online library market, and also the PlatformIO one.
  - https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ
  - https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format

- An example circuit, I'm confused about the example `dual_core_ESP` external circuit.

- `WattCalc.h` and `WattCalc.cpp`: try to find if you need to include `Arduino.h`, and it should be `<Arduino.h>` not `"Arduino.h"` in `WattCalc.cpp`.

- The target boards are not clear, but try to include `stdint.h` and use `uint8_t`, `uint16_t`, `uint32_t` instead of `int`, `long`, If you know that a variable will not be more than 255, use types `byte`, `unsigned char`, `uint8_t`, so you don't consume RAM and some boards like Arduino Uno are 8-bit AVR so using 8-bits variables will be faster (I don't know if `int approximateVoltRMS()` can return a high voltage like 220v...220v in the Arduino ADC?).

- Comment all the code and all the functions without an exception, and also write what to input and it's unit (ms, s, mV, V, mA, A, ...) and what will be the output and it's unit (`int WattCalc::calculateAmpRMS()` will return A or mA?).

- I don't know if you calculate this but you should target a specific "theory max calculation error" to get a reasonable error % (eg 1% max, 0.5%max, ...) to not consume a lot of CPU time.

Please feel free to close it.

**Comment by RippoZero** [comment]
Thank you for helping me out. I've adressed some of the issues you found.
